@echo off
:: Set title and encoding
title VietTourAudio - Launcher
chcp 65001 >nul
setlocal enabledelayedexpansion

set "ROOT=%~dp0"

:: -------------------------------------------------------------
:: CONFIGURATION
:: -------------------------------------------------------------
set "CLIENT_PORT=80"
set "API_PORT=8443"
set "API_BASE_URL=https://bkpvp.top:8443/api"
set "PUBLIC_BASE_URL=https://bkpvp.top:8443/uploads"
set "DOTNET_CONNECTION=server=localhost;port=3306;database=viettuoraudio;user=root;password=;SslMode=None;AllowPublicKeyRetrieval=True;"

echo =======================================================================
echo              VIETTOURAUDIO LAUNCHER (AUTO START STACK)
echo =======================================================================
echo.

:: 1. Check Database (MySQL)
echo [1/3] Đang kiểm tra Database (MySQL) tại cổng 3306...
netstat -ano | findstr /R /C:":3306 .*LISTENING" >nul 2>&1
if %ERRORLEVEL% equ 0 (
  echo   [OK] MySQL đang chạy bình thường.
) else (
  echo   [WARN] MySQL chưa khởi chạy. Đang khởi động XAMPP MySQL...
  if exist "C:\xampp\mysql\bin\mysqld.exe" (
    start /B "VietTourAudio - MySQL" "C:\xampp\mysql\bin\mysqld.exe" --defaults-file=C:\xampp\mysql\bin\my.ini
    timeout /t 3 /nobreak >nul
  ) else (
    where docker >nul 2>&1
    if !ERRORLEVEL! equ 0 (
      docker compose up -d mysql
      timeout /t 3 /nobreak >nul
    ) else (
      echo   [WARN] Không tìm thấy XAMPP MySQL hoặc Docker. Vui lòng tự chạy MySQL.
    )
  )
)

:: 2. Prepare Config files
echo.
echo [2/3] Đang chuẩn bị file cấu hình môi trường (.env.local)...
echo # Generated by run.bat at %DATE% %TIME% > "%ROOT%client\.env.local"
echo VITE_API_BASE_URL=%API_BASE_URL% >> "%ROOT%client\.env.local"
echo VITE_DEV_PORT=%CLIENT_PORT% >> "%ROOT%client\.env.local"
echo VITE_DEV_HOST=0.0.0.0 >> "%ROOT%client\.env.local"
echo   [OK] Đã cấu hình client/.env.local

echo # Generated by run.bat at %DATE% %TIME% > "%ROOT%client\web-admin\.env.local"
echo VITE_ADMIN_API_URL=%API_BASE_URL% >> "%ROOT%client\web-admin\.env.local"
echo VITE_API_BASE_URL=%API_BASE_URL% >> "%ROOT%client\web-admin\.env.local"
echo   [OK] Đã cấu hình client/web-admin/.env.local

:: Check node_modules
if not exist "%ROOT%client\node_modules" (
  echo   [!] Không tìm thấy node_modules của Client. Đang tiến hành cài đặt...
  pushd "%ROOT%client"
  call npm install
  popd
)

:: 3. Start services
echo.
echo [3/3] Đang khởi động các dịch vụ...

:: Tắt các tiến trình cũ để tránh xung đột cổng
taskkill /FI "WINDOWTITLE eq VietTourAudio - .NET API" /T /F >nul 2>&1
taskkill /FI "WINDOWTITLE eq VietTourAudio - Frontend" /T /F >nul 2>&1
taskkill /IM dotnet.exe /F >nul 2>&1

:: Khởi động Backend API
echo 1. Khởi động Backend API (.NET) trên cổng %API_PORT%...
start "VietTourAudio - .NET API" cmd /k "pushd "%ROOT%server\VietTourAudio.Api" && set ASPNETCORE_ENVIRONMENT=Development && set ASPNETCORE_URLS=http://*:%API_PORT% && set ConnectionStrings__DefaultConnection=%DOTNET_CONNECTION% && set Storage__PublicBaseUrl=%PUBLIC_BASE_URL% && dotnet run --no-launch-profile"

:: Khởi động Client
echo 2. Khởi động Frontend Client trên cổng %CLIENT_PORT%...
start "VietTourAudio - Frontend" cmd /k "pushd "%ROOT%client" && npm run dev"

echo.
echo =======================================================================
echo  Khởi động hoàn tất!
echo  - Giao diện Client: http://bkpvp.top (Cổng %CLIENT_PORT%)
echo  - Backend API:       https://bkpvp.top:%API_PORT%/api
echo  - Swagger UI:        https://bkpvp.top:%API_PORT%/swagger
echo =======================================================================
echo.
timeout /t 3 /nobreak >nul
start http://bkpvp.top
pause
