[CmdletBinding()]
param(
  [string]$ConfigPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'deployment\production.config.json'),
  [string]$OutputRoot = (Split-Path -Parent $PSScriptRoot),
  [switch]$Check
)

$ErrorActionPreference = 'Stop'
$utf8NoBom = New-Object Text.UTF8Encoding($false)
$configFile = [IO.Path]::GetFullPath($ConfigPath)
$outputRootPath = [IO.Path]::GetFullPath($OutputRoot)

if (-not (Test-Path -LiteralPath $configFile -PathType Leaf)) {
  throw "Central production config not found: $configFile"
}

$config = Get-Content -LiteralPath $configFile -Raw | ConvertFrom-Json
$rootDomain = ([string]$config.rootDomain).Trim().TrimEnd('.').ToLowerInvariant()
$serverIp = ([string]$config.serverIp).Trim()
$apiPrefix = ([string]$config.subdomains.api).Trim().ToLowerInvariant()
$adminPrefix = ([string]$config.subdomains.admin).Trim().ToLowerInvariant()
$vendorPrefix = ([string]$config.subdomains.vendor).Trim().ToLowerInvariant()

if ($rootDomain -notmatch '^(?=.{4,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$') {
  throw "Invalid rootDomain: $rootDomain"
}

$parsedIp = $null
if (-not [Net.IPAddress]::TryParse($serverIp, [ref]$parsedIp) -or
    $parsedIp.AddressFamily -ne [Net.Sockets.AddressFamily]::InterNetwork) {
  throw "serverIp must be a valid public IPv4 address: $serverIp"
}

$prefixes = @($apiPrefix, $adminPrefix, $vendorPrefix)
if (($prefixes | Where-Object { $_ -notmatch '^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$' }).Count -gt 0) {
  throw 'Subdomain prefixes may contain only letters, digits, and internal hyphens.'
}
if (($prefixes | Select-Object -Unique).Count -ne 3) {
  throw 'api, admin, and vendor subdomain prefixes must be unique.'
}

$apiHost = "$apiPrefix.$rootDomain"
$adminHost = "$adminPrefix.$rootDomain"
$vendorHost = "$vendorPrefix.$rootDomain"
$apiOrigin = "https://$apiHost"
$apiBaseUrl = "$apiOrigin/api"

$outputs = [ordered]@{}

foreach ($app in @(
  @{ Name = 'mobile'; Host = $rootDomain; Entry = '/' },
  @{ Name = 'admin'; Host = $adminHost; Entry = '/admin' },
  @{ Name = 'vendor'; Host = $vendorHost; Entry = '/vendor' }
)) {
  $envContent = @(
    '# Generated by scripts/Sync-ProductionConfig.ps1. Do not edit by hand.'
    "VITE_APP_ROLE=$($app.Name)"
    "VITE_APP_ENTRY_PATH=$($app.Entry)"
    "VITE_API_BASE_URL=$apiBaseUrl"
    "VITE_API_URL=$apiBaseUrl"
    "VITE_ADMIN_API_URL=$apiBaseUrl"
    "VITE_SOCKET_URL=$apiOrigin"
    "VITE_PUBLIC_APP_URL=https://$rootDomain"
    "VITE_GUEST_APP_URL=https://$rootDomain"
    ''
  ) -join [Environment]::NewLine
  $outputs["client\.env.production.$($app.Name)"] = $envContent
}

$productionSettings = [ordered]@{
  Production = [ordered]@{
    RootDomain = $rootDomain
    ServerIp = $serverIp
    ApiHost = $apiHost
    AdminHost = $adminHost
    VendorHost = $vendorHost
  }
  Storage = [ordered]@{
    PublicBaseUrl = "$apiOrigin/uploads"
  }
  Cors = [ordered]@{
    AllowedOrigins = @(
      "https://$rootDomain",
      "https://$adminHost",
      "https://$vendorHost"
    )
  }
  AllowedHosts = $apiHost
}
$outputs['server\VietTourAudio.Api\appsettings.Production.json'] =
  ($productionSettings | ConvertTo-Json -Depth 8) + [Environment]::NewLine

$generatedHosts = [ordered]@{
  rootDomain = $rootDomain
  serverIp = $serverIp
  hosts = [ordered]@{
    mobile = $rootDomain
    api = $apiHost
    admin = $adminHost
    vendor = $vendorHost
  }
}
$outputs['deployment\generated\hosts.json'] =
  ($generatedHosts | ConvertTo-Json -Depth 6) + [Environment]::NewLine

$changed = @()
foreach ($entry in $outputs.GetEnumerator()) {
  $target = Join-Path $outputRootPath $entry.Key
  $current = if (Test-Path -LiteralPath $target -PathType Leaf) {
    [IO.File]::ReadAllText($target)
  } else {
    $null
  }

  if ($current -cne $entry.Value) {
    $changed += $entry.Key
    if (-not $Check) {
      [IO.Directory]::CreateDirectory((Split-Path -Parent $target)) | Out-Null
      [IO.File]::WriteAllText($target, $entry.Value, $utf8NoBom)
    }
  }
}

if ($Check -and $changed.Count -gt 0) {
  throw "Generated production files are stale: $($changed -join ', '). Run scripts\Sync-ProductionConfig.ps1."
}

if ($changed.Count -eq 0) {
  Write-Host 'Production configuration is already synchronized.'
} elseif ($Check) {
  throw 'Production configuration is not synchronized.'
} else {
  Write-Host "Updated $($changed.Count) generated production file(s):"
  $changed | ForEach-Object { Write-Host "  $_" }
}

[pscustomobject]@{
  RootDomain = $rootDomain
  ServerIp = $serverIp
  ApiHost = $apiHost
  AdminHost = $adminHost
  VendorHost = $vendorHost
  ChangedFiles = $changed.Count
}
