// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VietTourAudio.Api.Data;

#nullable disable

namespace VietTourAudio.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701010843_AddPoiTrackingMetrics")]
    partial class AddPoiTrackingMetrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VietTourAudio.Api.Domain.AudioPlayEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("language_code");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("played_at");

                    b.Property<string>("PoiId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("poi_id");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("session_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("source");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("VendorId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id");

                    b.HasIndex("PoiId", "PlayedAt");

                    b.HasIndex("SessionId", "PlayedAt");

                    b.HasIndex("VendorId", "PlayedAt");

                    b.ToTable("audio_play_events", (string)null);
                });

            modelBuilder.Entity("VietTourAudio.Api.Domain.CauHinhThanhToan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("account_name");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("account_number");

                    b.Property<string>("GatewayType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("gateway_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("QrCodeUrl")
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)")
                        .HasColumnName("qr_code_url");

                    b.Property<string>("TransferMemoPattern")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("transfer_memo_pattern");

                    b.HasKey("Id");

                    b.HasIndex("GatewayType")
                        .IsUnique();

                    b.ToTable("admin_payment_configs", (string)null);
                });

            modelBuilder.Entity("VietTourAudio.Api.Domain.FestivalZone", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("cover_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<double>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("ZoneCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("zone_code");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("ZoneCode")
                        .IsUnique();

                    b.ToTable("FestivalZones", (string)null);
                });

            modelBuilder.Entity("VietTourAudio.Api.Domain.GiaoDichThanhToan", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PendingKey")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("pending_key");

                    b.Property<string>("ProofAttachmentUrl")
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)")
                        .HasColumnName("proof_attachment_url");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("sender_id");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sender_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("transaction_type");

                    b.Property<string>("TransferMemo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("transfer_memo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PendingKey")
                        .IsUnique();

                    b.HasIndex("TransferMemo")
                        .IsUnique();

                    b.ToTable("payment_transactions", (string)null);
                });

            modelBuilder.Entity("VietTourAudio.Api.Domain.GuestFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("added_at");

                    b.Property<string>("GuestId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("guest_id");

                    b.Property<string>("PoiId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("poi_id");

                    b.HasKey("Id");

                    b.HasIndex("PoiId");

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("VietTourAudio.Api.Domain.Poi", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("approval_status");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("cover_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("longtext")
                        .HasColumnName("description_en");

                    b.Property<string>("DescriptionJa")
                        .HasColumnType("longtext")
                        .HasColumnName("description_ja");

                    b.Property<string>("DescriptionKo")
                        .HasColumnType("longtext")
                        .HasColumnName("description_ko");

                    b.Property<string>("DescriptionZh")
                        .HasColumnType("longtext")
                        .HasColumnName("description_zh");

                    b.Property<string>("FestivalZoneId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("festival_zone_id");

                    b.Property<bool>("IsPremiumPriority")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_premium_priority");

                    b.Property<double>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<string>("PendingCoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("pending_cover_image_url");

                    b.Property<string>("PendingDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("pending_description");

                    b.Property<string>("PendingDescriptionEn")
                        .HasColumnType("longtext")
                        .HasColumnName("pending_description_en");

                    b.Property<string>("PendingDescriptionJa")
                        .HasColumnType("longtext")
                        .HasColumnName("pending_description_ja");

                    b.Property<string>("PendingDescriptionKo")
                        .HasColumnType("longtext")
                        .HasColumnName("pending_description_ko");

                    b.Property<string>("PendingDescriptionZh")
                        .HasColumnType("longtext")
                        .HasColumnName("pending_description_zh");

                    b.Property<double?>("PendingLatitude")
                        .HasColumnType("double")
                        .HasColumnName("pending_latitude");

                    b.Property<double?>("PendingLongitude")
                        .HasColumnType("double")
                        .HasColumnName("pending_longitude");

                    b.Property<string>("PendingName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pending_name");

                    b.Property<string>("PendingNameEn")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pending_name_en");

                    b.Property<string>("PendingNameJa")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pending_name_ja");

                    b.Property<string>("PendingNameKo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pending_name_ko");

                    b.Property<string>("PendingNameZh")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pending_name_zh");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("StallName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("stall_name");

                    b.Property<string>("StallNameEn")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("stall_name_en");

                    b.Property<string>("StallNameJa")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("stall_name_ja");

                    b.Property<string>("StallNameKo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("stall_name_ko");

                    b.Property<string>("StallNameZh")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("stall_name_zh");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<int>("TotalListens")
                        .HasColumnType("int")
                        .HasColumnName("total_listens");

                    b.Property<int>("TotalVisits")
                        .HasColumnType("int")
                        .HasColumnName("total_visits");

                    b.Property<double>("TriggerRadius")
                        .HasColumnType("double")
                        .HasColumnName("trigger_radius");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("VendorId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id");

                    b.HasIndex("FestivalZoneId");

                    b.HasIndex("VendorId");

                    b.ToTable("Pois", (string)null);
                });

            modelBuilder.Entity("VietTourAudio.Api.Domain.PoiProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("PoiId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("poi_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductNameEn")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("product_name_en");

                    b.Property<string>("ProductNameJa")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("product_name_ja");

                    b.Property<string>("ProductNameKo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("product_name_ko");

                    b.Property<string>("ProductNameZh")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("product_name_zh");

                    b.HasKey("Id");

                    b.HasIndex("PoiId");

                    b.ToTable("StallProducts", (string)null);
                });

            modelBuilder.Entity("VietTourAudio.Api.Domain.SystemTicket", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sender_email");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sender_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("subject");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("system_tickets", (string)null);
                });

            modelBuilder.Entity("VietTourAudio.Api.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsPremiumActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_premium_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pass_hash");

                    b.Property<DateTime?>("PremiumExpiryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("premium_expiry_date");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("VietTourAudio.Api.Domain.VendorProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FestivalZoneId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("festival_zone_id");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_premium");

                    b.Property<DateTime?>("PremiumActivationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("premium_activation_date");

                    b.Property<DateTime?>("PremiumExpiryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("premium_expiry_date");

                    b.Property<DateTime?>("SubscriptionExpiryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("subscription_expiry_date");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("trade_name");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FestivalZoneId");

                    b.ToTable("Vendors", (string)null);
                });

            modelBuilder.Entity("VietTourAudio.Api.Domain.VisitEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<decimal?>("DistanceMeters")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("distance_meters");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("PoiId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("poi_id");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("session_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("source");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("VendorId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("vendor_id");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("visited_at");

                    b.HasKey("Id");

                    b.HasIndex("PoiId", "VisitedAt");

                    b.HasIndex("SessionId", "VisitedAt");

                    b.HasIndex("VendorId", "VisitedAt");

                    b.ToTable("visit_events", (string)null);
                });

            modelBuilder.Entity("VietTourAudio.Api.Domain.Wallet", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("balance");

                    b.Property<decimal>("PromoBalance")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("promo_balance");

                    b.Property<decimal>("TotalSpent")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("total_spent");

                    b.Property<decimal>("TotalTopUp")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("total_top_up");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id");

                    b.HasIndex("VendorId")
                        .IsUnique();

                    b.ToTable("vendor_wallets", (string)null);
                });

            modelBuilder.Entity("VietTourAudio.Api.Domain.WalletTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("balance_after");

                    b.Property<decimal>("BalanceBefore")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("balance_before");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)")
                        .HasColumnName("description");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("direction");

                    b.Property<string>("TransactionCategory")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("transaction_category");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("transaction_type");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("vendor_id");

                    b.Property<string>("WalletId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("wallet_transactions", (string)null);
                });

            modelBuilder.Entity("VietTourAudio.Api.Domain.GuestFavorite", b =>
                {
                    b.HasOne("VietTourAudio.Api.Domain.Poi", "Poi")
                        .WithMany()
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("VietTourAudio.Api.Domain.Poi", b =>
                {
                    b.HasOne("VietTourAudio.Api.Domain.FestivalZone", "FestivalZone")
                        .WithMany("Pois")
                        .HasForeignKey("FestivalZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VietTourAudio.Api.Domain.VendorProfile", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("FestivalZone");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("VietTourAudio.Api.Domain.PoiProduct", b =>
                {
                    b.HasOne("VietTourAudio.Api.Domain.Poi", "Poi")
                        .WithMany("Products")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("VietTourAudio.Api.Domain.VendorProfile", b =>
                {
                    b.HasOne("VietTourAudio.Api.Domain.FestivalZone", "FestivalZone")
                        .WithMany("Vendors")
                        .HasForeignKey("FestivalZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FestivalZone");
                });

            modelBuilder.Entity("VietTourAudio.Api.Domain.Wallet", b =>
                {
                    b.HasOne("VietTourAudio.Api.Domain.VendorProfile", "Vendor")
                        .WithOne("Wallet")
                        .HasForeignKey("VietTourAudio.Api.Domain.Wallet", "VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("VietTourAudio.Api.Domain.WalletTransaction", b =>
                {
                    b.HasOne("VietTourAudio.Api.Domain.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("VietTourAudio.Api.Domain.FestivalZone", b =>
                {
                    b.Navigation("Pois");

                    b.Navigation("Vendors");
                });

            modelBuilder.Entity("VietTourAudio.Api.Domain.Poi", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("VietTourAudio.Api.Domain.VendorProfile", b =>
                {
                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("VietTourAudio.Api.Domain.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
